ChromeDriverPath="C:\\Users\\Sanelib Solutions\\PycharmProjects\\CmdStructureWise\\resources\\driver\\chromedriver.exe"
PhantomDriverPath="C:\\Users\\Sanelib Solutions\\PycharmProjects\\CmdStructureWise\\resources\\driver\\phantomjs.exe"

ConfigurationFile="C:\\Users\\Sanelib Solutions\\PycharmProjects\\CmdStructureWise\\automation\\framework\\configure.txt"
FlightSearchResultFile="C:\\Users\\Sanelib Solutions\\PycharmProjects\\CmdStructureWise\\resources\\vc.xlsx"
ScreenShotPath="C:\\Users\\Sanelib Solutions\\PycharmProjects\\CmdStructureWise\\resources\\Screenshots\\invalidlogin.png"
Browser="browser"
Url="url"
Username="username"
Password="password"
UserDisaplyName="user_Display_Name"
DCITY="DCITY"
ACITY="ACITY"
DepartureDate="DDate"
ArrivalDate="ADate"

Banner_SignOut="Sign Out"
Banner_SignIn="Sign In"
Banner_MyProfile="My Profile"

Dashboard_OneWay="One Way"
Dashboard_MyTrips="My Trips"
Dashboard_Inbox="Inbox"
Dashboard_Collections="Collections"
Dashboard_Profile="Profile"
Dashboard_InstantBookings="Instant Bookings"
Dashboard_RecentSearches="Recent Searches"
Dashboard_ContinuousSearches="Continuous Searches"
Dashboard_MyRequests="My Requests"
Dashboard_RecentlySavedToCollections="Recently Saved to Collections"
Dashboard_RecentBookings="Recent Bookings"

Home_About="About"
Home_List="List"
Home_News="News"
Home_Register="Register"
Home_RequestAnInvite="Request An Invite"
Home_RightProductRightTime="Right product. Right time."
Home_TheSearchIsOver="The search is over."
Home_EveryAspectOfYourTripIsHere="Every aspect of your trip is here."
Home_DontEmailLinksShareInspiration="Don’t email links. Share inspiration."

FlightSearch_ResultsExpireMsg="Results expire in"
RequiredFieldMsg="required field"
LoginValidationMsg="Please make sure email is valid"